#! /bin/bash
DO_ALL=1
DO_PREPROC=0
DO_ASN1=0
DO_DEPLOY=0

MACHINE=
if [ $(uname -m) == "armv7l" ]; then
	MACHINE=-arm32v7
fi

DOCKER_INVOCATION=
if [ x"" == x"${CI}" ]; then
	DOCKER_INVOCATION=docker run -v `pwd`:`pwd` -w `pwd` -u `id -u`:`id -g` vlinder/antlr4${MACHINE}
fi

while (( "$#" )); do
	case "$1" in
	-d)
		DO_ALL=0
		DO_DEPLOY=1
		;;
	-p)
		DO_ALL=0
		DO_PREPROC=1
		;;
	-a)
		DO_ALL=0
		DO_ASN1=1
		;;
	esac
	shift
done

if [ x"${DO_ALL}${DO_PREPROC}" != x"00" ]; then
	mkdir -p generated
	${DOCKER_INVOCATION} antlr4 -Dlanguage=Cpp -o generated preproc.g4
fi
if [ x"${DO_ALL}${DO_ASN1}" != x"00" ]; then
	mkdir -p generated
	${DOCKER_INVOCATION} antlr4 -Dlanguage=Cpp -o generated -visitor asn1.g4
fi
if [ x"${DO_ALL}${DO_DEPLOY}" != x"00" ]; then
	${DOCKER_INVOCATION} deploy -o antlr4
fi

