#include "catch.hpp"
#include "../runtime/objectidentifier.hpp"

using namespace Vlinder::Rubicon;

TEST_CASE( "Default-constructed ObjectIdentifiers are empty", "[objectidentifier]" ) {
    ObjectIdentifier oid;

    REQUIRE(oid.empty());
    REQUIRE(oid.size() == 0);
    REQUIRE(oid.begin() == oid.end());
}
SCENARIO( "ObjectIdentifier: when constructed by code as generated by the generator", "[objectidentifier]" )
{
	GIVEN( "an ObjectIdentifier with some value" )
	{

	}
}

