#! /usr/bin/env python3
import argparse
import subprocess

def run_compiler(asn1c_path, input_filename):
	pass

if (__name__ == "__main__"):
	parser = argparse.ArgumentParser()
	parser.add_argument("-c", "--asn1c", type=string, help="path to asn1c", default="./asn1c")
	args = parser.parse_args()
	print(args.asn1c)
